import pygame
from config.sudoku_config import * 

# Botones Menu
W_BOTON_MENU = 300
H_BOTON_MENU = 100
X_BOTON_MENU = (WIDTH - W_BOTON_MENU) // 2
Y_BOTON_MENU = (HEIGHT - H_BOTON_MENU) // 2 - 100

RECT_BOTON_1 = pygame.Rect(X_BOTON_MENU, Y_BOTON_MENU, W_BOTON_MENU, H_BOTON_MENU)
RECT_BOTON_2 = pygame.Rect(X_BOTON_MENU, Y_BOTON_MENU + H_BOTON_MENU + 20, W_BOTON_MENU, H_BOTON_MENU)
RECT_BOTON_3 = pygame.Rect(X_BOTON_MENU, Y_BOTON_MENU + (H_BOTON_MENU + 20) * 2, W_BOTON_MENU, H_BOTON_MENU)
RECT_BOTON_4 = pygame.Rect(X_BOTON_MENU, Y_BOTON_MENU + (H_BOTON_MENU + 20) * 3, W_BOTON_MENU, H_BOTON_MENU)

# Cuadro puntajes
W_PUNTAJES = 500
H_PUNTAJES = 350
X_PUNTAJES = (WIDTH - W_PUNTAJES) // 2
Y_PUNTAJES = (HEIGHT - H_PUNTAJES) // 2

RECT_PUNTAJES = pygame.Rect(X_PUNTAJES, Y_PUNTAJES, W_PUNTAJES, H_PUNTAJES)

W_NOMBRE = 500
H_NOMBRE = 150
X_NOMBRE = (WIDTH - W_BOTON_MENU) // 2
Y_NOMBRE = (HEIGHT - H_BOTON_MENU) // 2

RECT_PEDIR_NOMBRE = pygame.Rect(X_NOMBRE, Y_NOMBRE, W_NOMBRE, H_NOMBRE)

# Botones partida
X_BOTON = BOARD_WIDTH
Y_BOTON = BOARD_HEIGHT * 0.25

RECT_BOTON_VALIDAR = pygame.Rect(X_BOTON, Y_BOTON, VALIDATE_BTN_WIDTH, VALIDATE_BTN_HEIGHT)
RECT_BOTON_RESETEAR = pygame.Rect(X_BOTON, Y_BOTON + BOARD_PADDING * 3, VALIDATE_BTN_WIDTH, VALIDATE_BTN_HEIGHT)
RECT_BOTON_VOLVER = pygame.Rect(X_BOTON, Y_BOTON + BOARD_PADDING * 6, VALIDATE_BTN_WIDTH, VALIDATE_BTN_HEIGHT)

# Boton musica
DIMENSION_ICONO_MUSICA = 40
X_BOTON_MUSICA = 20
Y_BOTON_MUSICA = HEIGHT - DIMENSION_ICONO_MUSICA - 20

RECT_MUSICA = pygame.Rect(X_BOTON_MUSICA, Y_BOTON_MUSICA, DIMENSION_ICONO_MUSICA, DIMENSION_ICONO_MUSICA)

