# Pre cargar datos hardcodeados para debug
def pre_cargar_estudiantes():
    return calificaciones_estudiantes_inciales, nombres_estudiantes_iniciales, generos_estudiantes_iniciales, legajos_estudiantes_iniciales, estados_estudiantes_iniciales

calificaciones_estudiantes_inciales = [
                                        [10, 9, 7, 4, 8],
                                        [7, 9, 7, 5, 6],
                                        [2, 4, 7, 4, 5],
                                        [3, 3, 1, 4, 2],
                                        [10, 9, 7, 8, 10],
                                        [1, 1, 1, 5, 4],
                                        [2, 7, 7, 7, 9],
                                        [5, 4, 8, 4, 6],
                                        [6, 9, 8, 4, 2],
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,
                                        None,        
                                        ]

nombres_estudiantes_iniciales = [
                        "Juan Perez",
                        "Romina Balladares",
                        "Joaquin Garcia",
                        "Antonella Castro",
                        "Facundo Casaccio",
                        "Leonardo Kdouh",
                        "Catalina Astra",
                        "Melina Edet",
                        "Julian Gonzalez",
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,
                        None,    
                        ]

generos_estudiantes_iniciales = [
                                "M",
                                "F",
                                "M",
                                "F",
                                "M",
                                "M",
                                "X",
                                "F",
                                "M",
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,    
                                ]


legajos_estudiantes_iniciales =[
                                "991282",
                                "991238",
                                "098123",
                                "678321",
                                "222222",
                                "896213",
                                "890675",
                                "328974",
                                "118936",
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,
                                None,    
                                ]

estados_estudiantes_iniciales = [
                                1,
                                1,
                                1,
                                1,
                                1,
                                1,
                                1,
                                1,
                                1,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0
                                ]